### ISSUE TITLE
Typo in code .fild_files instead of .find_files

### ISSUE THREAD

**Issue by umbrellaid** [alextricity25/nvim_weekly_plugin_configs#1]
https://github.com/alextricity25/nvim_weekly_plugin_configs/blame/d4c6c786214eb4968bee131f853d354a2153b334/lua/keymappings.lua#L37C30-L37C31

I think you may have a typo in code .fild_files instead of .find_files, Forgive me if I am wrong, I am just learning neovim and I see an error on this line when trying to run your config to see how it works.

**Comment by alextricity25** [comment]
You are correct! Nice catch! I'll get that patched up ^.^
